load data local infile '../source_data/anagrafica.csv' INTO TABLE anagrafica FIELDS terminated BY ','
OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (@col1,
						@col2,
						@col3,
						@col4,
						@col5,
						@col6,
						@col7,
						@col8,
						@col9,
						@col10,
						@col11,
						@col12,
						@col13,
						@col14,
						@col15,
						@col16,
						@col17,
						@col18,
						@col19,
						@col20,
						@col21,
						@col22,
						@col23,
						@col24,
						@col25,
						@col26,
						@col27,
						@col28,
						@col29,
						@col30,
						@col31,
						@col32,
						@col33,
						@col34,
						@col35,
						@col36,
						@col37,
						@col38,
						@col39,
						@col40,
						@col41,
						@col42,
						@col43,
						@col44,
						@col45,
						@col46,
						@col47,
						@col48,
						@col49,
						@col50,
						@col51
)
      set id=@col1,
      n_socio=@col2,
      id_sottosezione=@col4,
      id_categoria=@col5,
      id_gruppo_par=(SELECT id FROM gruppo_parrocchiale
                     WHERE  id_sottosezione=TRIM(@col4)
                     AND    id_ori=TRIM(@col7)),
      id_tipo_personale=@col8,
      id_stato_civile=@col9,
      id_professione=@col10,
      id_titolo_studio=@col11,
      indirizzo=@col15,
      citta=CONCAT(TRIM(@col16),' (',TRIM(@col17),')'),
      cap=@col18,
      data_nascita=CONCAT(@col19,'-',@col20,'-',@col21),
      luogo_nascita=TRIM(@col22),
      sesso=@col23,
      cf=TRIM(@col24),
      telefono=@col25,
      id_tipo_doc=@col26,
      n_doc=@col27,
      data_ril=CONCAT(@col28,'-',@col29,'-',@col30),
      deceduto=@col38,
      socio_effettivo=@col39,
      pensionato=@col40,
      nome=TRIM(@col45),
      cognome=TRIM(@col46),
      codice_catastale=TRIM(@col48),
      id_provincia=(SELECT id FROM province WHERE sigla=TRIM(@col17)),
      n_tessera_unitalsi=@col50,
      id_sezione=1,
      id_classificazione=2,
      ts=@col51;
